### ISSUE TITLE
Application Deployment

### ISSUE THREAD

**Issue by swashcap** [swashcap/portland-cafes#2]
We need to figure out a way to reliably deploy the application. I’m making this issue to keep track of our options.

**Comment by swashcap** [comment]
[Dploy](http://dploy.io/) by Beanstalk is an option. Their process:

> 1. Initiate a deployment
> 2. We detect the changes
> 3. Deployment is triggered
> 4. Team is notified

They “SSH commands are executed and deployment hooks are triggered” in step 3. We’d have to set up the server to do builds.

**Comment by swashcap** [comment]
[Circle CI](https://circleci.com/) is another option that offers lots of customization. It’s focused more on continuous integration through testing.

**Comment by swashcap** [comment]
[Codeship](https://codeship.com) is another option.

**Comment by swashcap** [comment]
…and there’s also [Deploy](https://www.deployhq.com/), which doesn’t seem to run any tests.

**Comment by dlachasse** [comment]
I was just checking out Deploy, they seem to be pretty easy to set up. It seems like the CI route might not be a bad one. Even though we don't have many tests now it's encouragement to write more and offers a really easy, hosted solution. That means one less tool to have to actually worry about. I actually saw Chris set it up for a project and it worked from the start with minimal config. CircleCI and Codeship both seem like great options, though that _sweet_ button on their home page makes me want to use it even more.

**Comment by swashcap** [comment]
Test comment: we’re working on [DeployHQ](https://www.deployhq.com/) for this.

**Comment by swashcap** [comment]
Closing this issue. We’re all set up on DeployHQ.
