### ISSUE TITLE
Pagination breaks when moving past page 2

### ISSUE THREAD

**Issue by dlachasse** [swashcap/portland-cafes#7]
After you pass page 2 on the pagination, page 1 shows up as page 0 and counts up from there. 

![screen shot 2015-02-13 at 5 11 18 pm](https://cloud.githubusercontent.com/assets/906387/6197917/5bb268b0-b3a3-11e4-8254-08e60dbc8107.png)

![screen shot 2015-02-13 at 5 09 32 pm](https://cloud.githubusercontent.com/assets/906387/6197906/2e3932d8-b3a3-11e4-851e-3c2b811d7c08.png)

**Comment by swashcap** [comment]
b49a5db94653647a843dfa472dadc4336d51367d addes a test for the appropriate method and 9e2d7acba35e8c3a19df72f53fa7c33daaa4a54f fixes this issue.
